### PR TITLE
lodash: changed _.partition() method

### PR DESCRIPTION
**Pull request by chrootsu**
I never changed on someone else's PR, but I think that it's done something like that. ^_^

### CODE REVIEW

**Comment by splintor** [comment]
Looks great. Thanks!

**Comment by chrootsu** [comment]
No thanks at all )
Now you can merge the pull request and the commit should be added to https://github.com/borisyankov/DefinitelyTyped/pull/5284

**Comment by splintor** [comment]
Done. Let me know if anything else is needed.

**Comment by chrootsu** [comment]
Thanks! Nothing more is needed.

**Pull request merged**
